sudo: false
dist: xenial
language: python
matrix:
  include:
    # test on 3.4, 3.5, 3.6
    - python: "3.5"
      env: TOXENV=py
    - python: "3.6"
      env: TOXENV=py,lowestdeps
    # separate py3.6 linting build, which runs 'black --check' (no py2 support)
    - name: "Python: 3.6 (linting)"
      python: "3.6"
      env: TOXENV=py36-lint
    - python: "3.7"
      env: TOXENV=py
    - python: "3.8"
      env: TOXENV=py
    - python: "nightly"
      env: TOXENV=py
    # non-Linux testing
    #   https://docs.travis-ci.com/user/languages/python/#running-python-tests-on-multiple-operating-systems
    #
    # Windows
    - name: "py3.8 + windows"
      os: windows
      language: shell
      env: TOXENV=py,lowestdeps,py38-lint PATH=/c/Python38:/c/Python38/Scripts:$PATH
      before_install:
        - choco install python3
        - python -m pip install --upgrade pip wheel
    # macOS
    - name: "py3 + macOS"
      os: osx
      osx_image: xcode10.2  # py3.7 on macOS 10.14
      language: shell
      env: TOXENV=py3,py3-lowestdeps,py37-lint

  allow_failures:
    - python: "nightly"
cache: pip
install:
  - pip install -e '.[development]'
script:
  - tox
